### PR TITLE
Team

### PR DESCRIPTION
**Pull request by SaiRohithEnumala8373**

### CODE REVIEW

**Comment by SaiRohithEnumala8373** [comment]
Fixed some minor issues, added hyperlinks to phone and email

**Comment by paulrang** [comment]
👍

**Comment by SaiRohithEnumala8373** [comment]
Thank you.

**Comment by SaiRohithEnumala8373** [comment]
Now, the hyperlinks look cool.

**Comment by boulongadong** [comment]
Sweet!

**Pull request merged**
