### PR TITLE
Removed default super user

### LINKED ISSUE #306: Remove the default admin user
Implement user logon

### PR DESCRIPTION
**Pull request by onlinestang**
added the ability to login from the database using emails.

Changed admin view for non super users

closes #306

### CODE REVIEW

**Comment by onlinestang** [comment]
Note that after this pull the default admin credentials will no longer log you in

**Comment by SaiRohithEnumala8373** [comment]
Nice!

**Comment by onlinestang** [comment]
> Nice!

Thank you

**Comment by boulongadong** [comment]
Nice!

**Pull request merged**
