### PR TITLE
Create branch with .ENV changes

### PR DESCRIPTION
**Pull request by onlinestang**
Will work off of this branch for a minute

Credentials all moved to credentials.js

### CODE REVIEW

**Comment by onlinestang** [comment]
Important branch going forward

**Comment by onlinestang** [comment]
Going to add order fulfillment as well

**Comment by paulrang** [comment]
Scary, but hopefully functional.

**Comment by onlinestang** [comment]
> Scary, but hopefully functional.

Paul I would like to remind you that at this point it literally cannot get any scarier.

**Pull request merged**
